/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs. 
 *
 * The version of the OpenAPI document: 
 * Contact: hi@ory.sh
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;
use std::borrow::Borrow;
use std::pin::Pin;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use hyper_util::client::legacy::connect::Connect;
use futures::Future;

use crate::models;
use super::{Error, configuration};
use super::request as __internal_request;

pub struct WellknownApiClient<C: Connect>
    where C: Clone + std::marker::Send + Sync + 'static {
    configuration: Arc<configuration::Configuration<C>>,
}

impl<C: Connect> WellknownApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    pub fn new(configuration: Arc<configuration::Configuration<C>>) -> WellknownApiClient<C> {
        WellknownApiClient {
            configuration,
        }
    }
}

pub trait WellknownApi: Send + Sync {
    fn discover_json_web_keys(&self, ) -> Pin<Box<dyn Future<Output = Result<models::JsonWebKeySet, Error>> + Send>>;
}

impl<C: Connect>WellknownApi for WellknownApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    #[allow(unused_mut)]
    fn discover_json_web_keys(&self, ) -> Pin<Box<dyn Future<Output = Result<models::JsonWebKeySet, Error>> + Send>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/.well-known/jwks.json".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

}
